---
- name: "Install pip to manage python packages"
  package:
    name: "python3-pip"
    state: "present"

- name: "Install the passlib python library"
  pip:
    name: "passlib"
    state: "latest"
