---
- name: "Create the dir for htaccess"
  file:
    path: "{{ prometheus_proxy_htaccess_path | dirname }}"
    state: "directory"
    mode: "u=rx,g=rx,o="
    owner: "{{ prometheus_proxy_htaccess_owner }}"
    group: "{{ prometheus_proxy_htaccess_owner }}"

- name: "Create the .htaccess file"
  htpasswd:
    path: "{{ prometheus_proxy_htaccess_path }}"
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    mode: "u=r,g=r,o="
    owner: "{{ prometheus_proxy_htaccess_owner }}"
    group: "{{ prometheus_proxy_htaccess_owner }}"
  with_items: "{{ prometheus_proxy_users }}"

- include: "proxies/{{ prometheus_proxy_webserver|lower }}.yml"
