---
# Exposes the exporters via the webserver, in a password protected way.
- name: "Create the vhosts"
  template:
    src: "etc/nginx/sites-enabled/template.conf"
    dest: "/etc/nginx/sites-enabled/{{ item.name }}.conf"
  with_items: "{{ prometheus_proxy_exporters }}"
  ## This comes from the upstream geerlingguy.nginx task
  notify: "reload nginx"
